# Generated by Django 4.2.30 on 2026-06-24 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0013_alter_rentalapplication_application_pdf'),
        ('properties', '0008_alter_propertyimage_image'),
        ('scheduler', '0003_viewing_email_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, help_text='Requested time slot', max_length=60)),
                ('tour_type', models.CharField(blank=True, default='self-tour', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('id_front', models.URLField(blank=True, max_length=600)),
                ('id_back', models.URLField(blank=True, max_length=600)),
                ('status', models.CharField(choices=[('AWAITING_ID', 'Awaiting ID'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='AWAITING_ID', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_requests', to='crm.lead')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_requests', to='properties.property')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tour_requests', to=settings.AUTH_USER_MODEL)),
                ('viewing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_requests', to='scheduler.viewing')),
            ],
            options={
                'verbose_name': 'Tour Request',
                'verbose_name_plural': 'Tour Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='scheduler_t_status_e2965b_idx')],
            },
        ),
    ]
