# Generated by Django 5.1.15 on 2026-04-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='profile_photo'),
        ),
    ]
