# Generated by Django 4.2.30 on 2026-06-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='agent_avatars/', verbose_name='profile_photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
