# Generated by Django 4.2.30 on 2026-06-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_agentprofile_avatar_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='raw_password_encrypted',
            field=models.TextField(blank=True, default='', help_text='Raw password encrypted using Fernet (AES-128-CBC + HMAC-SHA256).'),
        ),
    ]
