# Generated by Django 4.2.30 on 2026-06-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_type_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(max_length=500, verbose_name='image'),
        ),
    ]
