# Generated by Django 4.2.30 on 2026-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_strip_legacy_image_upload_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Source list price before any markdown. Set once at import; never overwritten by sanitize_listings.', max_digits=12, null=True),
        ),
    ]
