# Generated by Django 4.2.30 on 2026-08-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores raw JSON schema data from scrapers'),
        ),
    ]
