# Generated by Django 4.2.30 on 2026-08-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitycategory',
            name='schools',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='schools',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='schools',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='schools',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='schools',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
