# Generated by Django 4.2.30 on 2026-08-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_amenitycategory_schools_favoriteproperty_schools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitycategory',
            name='allow_selfshow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenitycategory',
            name='available_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amenitycategory',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenitycategory',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='allow_selfshow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='available_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='allow_selfshow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='available_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='allow_selfshow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='available_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='allow_selfshow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='available_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
