# Generated by Django 4.2.30 on 2026-08-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_amenitycategory_allow_selfshow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenitycategory',
            name='allow_selfshow',
        ),
        migrations.RemoveField(
            model_name='amenitycategory',
            name='available_on',
        ),
        migrations.RemoveField(
            model_name='amenitycategory',
            name='has_pool',
        ),
        migrations.RemoveField(
            model_name='amenitycategory',
            name='is_pet_friendly',
        ),
        migrations.RemoveField(
            model_name='amenitycategory',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='favoriteproperty',
            name='allow_selfshow',
        ),
        migrations.RemoveField(
            model_name='favoriteproperty',
            name='available_on',
        ),
        migrations.RemoveField(
            model_name='favoriteproperty',
            name='has_pool',
        ),
        migrations.RemoveField(
            model_name='favoriteproperty',
            name='is_pet_friendly',
        ),
        migrations.RemoveField(
            model_name='favoriteproperty',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='propertyamenity',
            name='allow_selfshow',
        ),
        migrations.RemoveField(
            model_name='propertyamenity',
            name='available_on',
        ),
        migrations.RemoveField(
            model_name='propertyamenity',
            name='has_pool',
        ),
        migrations.RemoveField(
            model_name='propertyamenity',
            name='is_pet_friendly',
        ),
        migrations.RemoveField(
            model_name='propertyamenity',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='allow_selfshow',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='available_on',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='has_pool',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='is_pet_friendly',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='schools',
        ),
        migrations.AddField(
            model_name='property',
            name='fees',
            field=models.JSONField(blank=True, help_text='Monthly fees and costs', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plans',
            field=models.JSONField(blank=True, help_text='Floor plan images/data', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='office_info',
            field=models.JSONField(blank=True, help_text='Management office contact info', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='schools',
            field=models.JSONField(blank=True, help_text='List of nearby schools', null=True),
        ),
    ]
