# Generated by Django 4.2.30 on 2026-06-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='file'),
        ),
    ]
