# Generated by Django 4.2.30 on 2026-07-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MARKET_ANALYSIS', 'Market Analysis'), ('BUYERS_GUIDE', "Buyer's Guide"), ('SELLERS_GUIDE', "Seller's Guide"), ('INVESTMENT', 'Investment'), ('MARKET_UPDATE', 'Market Update'), ('RENTER_GUIDE', "Renter's Guide")], max_length=30),
        ),
    ]
