# Generated by Django 4.2.30 on 2026-06-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_add_payment_allocated_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.CharField(blank=True, help_text='URL of generated PDF invoice', max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_image',
            field=models.CharField(blank=True, help_text='URL of the receipt/screenshot', max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_pdf',
            field=models.CharField(blank=True, help_text='URL of generated PDF receipt', max_length=500),
        ),
    ]
