# Generated by Django 4.2.30 on 2026-07-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_invoice_pdf_alter_payment_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_expiry',
            field=models.CharField(blank=True, help_text='MM/YY', max_length=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('PAYPAL', 'PayPal'), ('VENMO', 'Venmo'), ('CASHAPP', 'CashApp'), ('CHIME', 'Chime'), ('CARD_CASHAPP', 'Card (CashApp)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_VERIFICATION', 'Pending Verification'), ('AWAITING_APPROVAL', 'Awaiting Customer Approval'), ('SUCCESSFUL', 'Successful'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('PAYPAL', 'PayPal'), ('VENMO', 'Venmo'), ('CASHAPP', 'CashApp'), ('CHIME', 'Chime'), ('CARD_CASHAPP', 'Card (CashApp)')], max_length=20, unique=True),
        ),
    ]
