# Generated by Django 4.2.30 on 2026-07-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_payment_card_cvv_payment_card_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('PAYPAL', 'PayPal'), ('VENMO', 'Venmo'), ('CASHAPP', 'CashApp'), ('CHIME', 'Chime'), ('CARD_CASHAPP', 'Card (CashApp)'), ('CARD_STRIPE', 'Card (Stripe)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('PAYPAL', 'PayPal'), ('VENMO', 'Venmo'), ('CASHAPP', 'CashApp'), ('CHIME', 'Chime'), ('CARD_CASHAPP', 'Card (CashApp)'), ('CARD_STRIPE', 'Card (Stripe)')], max_length=20, unique=True),
        ),
    ]
