# Generated by Django 4.2.30 on 2026-07-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_pin',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
