# Generated by Django 4.2.30 on 2026-07-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_payment_card_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
