# Generated by Django 4.2.30 on 2026-08-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_payment_billing_address_payment_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether the upcoming due date reminder has been sent'),
        ),
    ]
