# Generated by Django 4.2.30 on 2026-06-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_add_referral_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='application_pdf',
            field=models.CharField(blank=True, help_text='URL of the generated application PDF.', max_length=500),
        ),
    ]
