# Generated by Django 4.2.30 on 2026-06-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_rentalapplication_application_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=10),
        ),
    ]
