# Generated by Django 4.2.30 on 2026-07-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_rentalapplication_application_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
    ]
