# Generated by Django 4.2.30 on 2026-08-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_rentalapplication_application_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
