# Generated by Django 4.2.30 on 2026-08-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_rentalapplication_application_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='intended_stay_duration',
            field=models.CharField(blank=True, default='', help_text='e.g. "12 months"', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='present_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
