# Generated by Django 4.2.30 on 2026-08-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_rentalapplication_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Custom security deposit. If left blank, it defaults to one month's rent.", max_digits=12, null=True),
        ),
    ]
