# Generated by Django 4.2.30 on 2026-08-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_rentalapplication_security_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='lease_admin_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional lease administration fee (e.g. 150.00).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='pet_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional pet fee.', max_digits=12, null=True),
        ),
    ]
