# Generated by Django 4.2.30 on 2026-09-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_rentalapplication_lease_admin_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=10),
        ),
    ]
