# Generated by Django 4.2.30 on 2026-06-18 01:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('max_scroll_depth', models.FloatField(default=0.0, help_text='Percentage 0.0 to 100.0')),
                ('idle_time', models.FloatField(default=0.0, help_text='Idle time in seconds')),
            ],
            options={
                'verbose_name': 'Page Visit',
                'verbose_name_plural': 'Page Visits',
                'ordering': ['entry_time'],
            },
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 18, 1, 30, 38, 679042, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='total_dwell_time',
            field=models.FloatField(default=0.0, help_text='Total active time in seconds'),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.pagevisit')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitorsession')),
            ],
            options={
                'verbose_name': 'Telemetry Event',
                'verbose_name_plural': 'Telemetry Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to='analytics.visitorsession'),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.visitor'),
        ),
    ]
