# Generated by Django 4.2.30 on 2026-06-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_pagevisit_visitorsession_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Raw Telemetry Event',
                'verbose_name_plural': 'Raw Telemetry Events (spool)',
                'ordering': ['received_at'],
                'indexes': [models.Index(fields=['processed', 'received_at'], name='analytics_r_process_26a8cb_idx')],
            },
        ),
    ]
