# Generated by Django 4.2.30 on 2026-07-23 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rawtelemetryevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='associated_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='visitor',
            name='first_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_lead',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='primary_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='primary_device',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='searched_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visitor',
            name='total_dwell_time',
            field=models.FloatField(default=0.0, help_text='Cumulative active time across all sessions in seconds'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='total_sessions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='viewed_property_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='connection_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='device_memory',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='hardware_concurrency',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='max_touch_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='orientation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='pixel_ratio',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='price_range_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='price_range_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='properties_viewed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='searched_cities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='viewport',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='telemetryevent',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='telemetryevent',
            index=models.Index(fields=['event_type', 'created_at'], name='analytics_t_event_t_2806f6_idx'),
        ),
    ]
